package com.checkout.backend.investment_portfolio.trade_order.dto;

import com.checkout.backend.investment_portfolio.trade_order.model.OrderSide;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.UUID;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

// clientOrderId is generated by the client .
// Double submit is rejected with 409.

@Getter @Setter
@NoArgsConstructor @AllArgsConstructor
@Builder
public class TradeOrderRequest {

    @NotNull
    private UUID clientOrderId;

    @NotNull
    private Long assetId;

    @NotNull
    private OrderSide side;

    @NotNull
    @DecimalMin(value = "0.0", inclusive = false,
            message = "The quantity must be greater than zero")
    private BigDecimal quantity;
}