-- V1: esquema base de Check-Out.
--
-- Generado con pg_dump contra el esquema que Hibernate creo a partir de las
-- entidades, no escrito a mano: asi lo que esta aqui es exactamente lo que el
-- modelo describe, y ddl-auto=validate lo confirma en cada arranque.
--
-- A partir de ahora el esquema lo manda este directorio, no Hibernate. Un
-- cambio en una @Entity necesita su propio V2__descripcion.sql; si falta, la
-- aplicacion no arranca y el mensaje dice que tabla o columna no cuadra. Eso es
-- deliberado: es la diferencia entre enterarse al desplegar y enterarse cuando
-- un usuario pierde datos.
--
-- Al regenerarlo con pg_dump hay que quitar dos cosas que no son SQL: el
-- preambulo de SET/SELECT y los meta-comandos de psql, las lineas que empiezan
-- por barra invertida. PostgreSQL 16 emite \restrict y \unrestrict, y Flyway
-- las rechaza con «syntax error at or near "\"».
--
-- Nunca se edita una migracion ya aplicada: Flyway guarda su checksum en
-- flyway_schema_history y se niega a seguir si cambia.



CREATE TABLE public.asset_price_history (
    id bigint NOT NULL,
    close_price numeric(19,4) NOT NULL,
    date date NOT NULL,
    asset_id bigint NOT NULL
);

ALTER TABLE public.asset_price_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_price_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.asset_quotes (
    id bigint NOT NULL,
    change_percent numeric(9,4),
    previous_close numeric(19,4),
    price numeric(19,4) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    asset_id bigint NOT NULL
);

ALTER TABLE public.asset_quotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.asset_quotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.assets (
    id bigint NOT NULL,
    active boolean NOT NULL,
    currency character varying(3) NOT NULL,
    name character varying(120) NOT NULL,
    symbol character varying(15) NOT NULL,
    type character varying(20) NOT NULL,
    CONSTRAINT assets_type_check CHECK (((type)::text = ANY ((ARRAY['ETF'::character varying, 'FUND'::character varying, 'STOCK'::character varying])::text[])))
);

ALTER TABLE public.assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    category character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date date NOT NULL,
    description character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT expenses_category_check CHECK (((category)::text = ANY ((ARRAY['FOOD'::character varying, 'TRANSPORT'::character varying, 'SERVICES'::character varying, 'EDUCATION'::character varying, 'LEISURE'::character varying, 'HEALTH'::character varying, 'OTHER'::character varying])::text[])))
);

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.incomes (
    id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    date date NOT NULL,
    description character varying(255),
    source character varying(100) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.incomes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.incomes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.investment_portfolios (
    id bigint NOT NULL,
    invested_tokens numeric(19,2) NOT NULL,
    realized_pnl numeric(19,2) NOT NULL,
    simulated_value numeric(19,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.investment_portfolios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.investment_portfolios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.minigame_sessions (
    id bigint NOT NULL,
    played_at timestamp(6) without time zone NOT NULL,
    score integer NOT NULL,
    tokens_earned numeric(19,2) NOT NULL,
    tokens_spent numeric(19,2) NOT NULL,
    minigame_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT minigame_sessions_score_check CHECK ((score >= 0))
);

ALTER TABLE public.minigame_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.minigame_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.minigames (
    id bigint NOT NULL,
    max_token_reward numeric(19,2) NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(120) NOT NULL,
    token_cost numeric(19,2) NOT NULL,
    topic character varying(120),
    type character varying(20) NOT NULL,
    CONSTRAINT minigames_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying])::text[]))),
    CONSTRAINT minigames_type_check CHECK (((type)::text = ANY ((ARRAY['TRIVIA'::character varying, 'SIMULATION'::character varying, 'QUIZ'::character varying])::text[])))
);

ALTER TABLE public.minigames ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.minigames_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.orders (
    id bigint NOT NULL,
    client_order_id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    executed_at timestamp(6) without time zone,
    execution_price numeric(19,4),
    quantity numeric(19,8) NOT NULL,
    rejection_reason character varying(255),
    side character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    token_rate numeric(19,8),
    tokens_moved numeric(19,2),
    asset_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT orders_side_check CHECK (((side)::text = ANY ((ARRAY['BUY'::character varying, 'SELL'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'EXECUTED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.portfolio_positions (
    id bigint NOT NULL,
    average_cost numeric(19,4) NOT NULL,
    quantity numeric(19,8) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    asset_id bigint NOT NULL,
    portfolio_id bigint NOT NULL
);

ALTER TABLE public.portfolio_positions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_positions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.projections (
    id bigint NOT NULL,
    annual_rate numeric(7,6) NOT NULL,
    calculated_at timestamp(6) without time zone NOT NULL,
    compound_final_amount numeric(19,2),
    initial_capital numeric(19,2) NOT NULL,
    monthly_contribution numeric(19,2) NOT NULL,
    name character varying(120) NOT NULL,
    periods integer NOT NULL,
    simple_final_amount numeric(19,2),
    savings_goal_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT projections_periods_check CHECK (((periods <= 600) AND (periods >= 1)))
);

ALTER TABLE public.projections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.projections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked_at timestamp(6) without time zone,
    token_hash character varying(255) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.savings (
    id bigint NOT NULL,
    current_balance numeric(19,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.savings_goal_contributions (
    id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reference_id bigint,
    source character varying(20) NOT NULL,
    savings_goal_id bigint NOT NULL,
    CONSTRAINT savings_goal_contributions_source_check CHECK (((source)::text = ANY ((ARRAY['MANUAL'::character varying, 'INCOME'::character varying, 'ADJUSTMENT'::character varying])::text[])))
);

ALTER TABLE public.savings_goal_contributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.savings_goal_contributions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.savings_goals (
    id bigint NOT NULL,
    accumulated_amount numeric(19,2) NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    deadline date NOT NULL,
    name character varying(120) NOT NULL,
    status character varying(20) NOT NULL,
    target_amount numeric(19,2) NOT NULL,
    version bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT savings_goals_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'EXPIRED'::character varying])::text[])))
);

ALTER TABLE public.savings_goals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.savings_goals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.savings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.savings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.token_transactions (
    id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    balance_after numeric(19,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason character varying(30) NOT NULL,
    reference_id bigint,
    token_wallet_id bigint NOT NULL,
    CONSTRAINT ck_token_tx_amount_not_zero CHECK ((amount <> (0)::numeric)),
    CONSTRAINT token_transactions_reason_check CHECK (((reason)::text = ANY ((ARRAY['GOAL_COMPLETED'::character varying, 'MINIGAME'::character varying, 'INVESTMENT'::character varying, 'ADJUSTMENT'::character varying])::text[])))
);

ALTER TABLE public.token_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.token_wallets (
    id bigint NOT NULL,
    token_balance numeric(19,2) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    version bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.token_wallets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role character varying(20) NOT NULL,
    CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['GUEST'::character varying, 'USER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    birth_date date,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(180) NOT NULL,
    name character varying(120) NOT NULL,
    password_hash character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.asset_price_history
    ADD CONSTRAINT asset_price_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.asset_quotes
    ADD CONSTRAINT asset_quotes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT assets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.incomes
    ADD CONSTRAINT incomes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.investment_portfolios
    ADD CONSTRAINT investment_portfolios_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.minigame_sessions
    ADD CONSTRAINT minigame_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.minigames
    ADD CONSTRAINT minigames_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portfolio_positions
    ADD CONSTRAINT portfolio_positions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.projections
    ADD CONSTRAINT projections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.savings_goal_contributions
    ADD CONSTRAINT savings_goal_contributions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.savings_goals
    ADD CONSTRAINT savings_goals_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.savings
    ADD CONSTRAINT savings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.token_transactions
    ADD CONSTRAINT token_transactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.token_wallets
    ADD CONSTRAINT token_wallets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.asset_price_history
    ADD CONSTRAINT uk_asset_price_history_asset_date UNIQUE (asset_id, date);

ALTER TABLE ONLY public.asset_quotes
    ADD CONSTRAINT uk_asset_quotes_asset UNIQUE (asset_id);

ALTER TABLE ONLY public.assets
    ADD CONSTRAINT uk_assets_symbol UNIQUE (symbol);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uk_orders_client_order_id UNIQUE (client_order_id);

ALTER TABLE ONLY public.investment_portfolios
    ADD CONSTRAINT uk_portfolios_user UNIQUE (user_id);

ALTER TABLE ONLY public.portfolio_positions
    ADD CONSTRAINT uk_positions_portfolio_asset UNIQUE (portfolio_id, asset_id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk_refresh_tokens_hash UNIQUE (token_hash);

ALTER TABLE ONLY public.savings
    ADD CONSTRAINT uk_savings_user UNIQUE (user_id);

ALTER TABLE ONLY public.token_transactions
    ADD CONSTRAINT uk_token_tx_reason_reference UNIQUE (reason, reference_id);

ALTER TABLE ONLY public.token_wallets
    ADD CONSTRAINT uk_token_wallets_user UNIQUE (user_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE INDEX idx_asset_price_history_asset_date ON public.asset_price_history USING btree (asset_id, date);

CREATE INDEX idx_expenses_user_date ON public.expenses USING btree (user_id, date);

CREATE INDEX idx_goal_contributions_goal_created ON public.savings_goal_contributions USING btree (savings_goal_id, created_at);

CREATE INDEX idx_incomes_user_date ON public.incomes USING btree (user_id, date);

CREATE INDEX idx_minigame_sessions_user_played ON public.minigame_sessions USING btree (user_id, played_at);

CREATE INDEX idx_orders_user_created ON public.orders USING btree (user_id, created_at);

CREATE INDEX idx_positions_portfolio ON public.portfolio_positions USING btree (portfolio_id);

CREATE INDEX idx_projections_user_calculated ON public.projections USING btree (user_id, calculated_at);

CREATE INDEX idx_refresh_tokens_user ON public.refresh_tokens USING btree (user_id);

CREATE INDEX idx_savings_goals_user_status_deadline ON public.savings_goals USING btree (user_id, status, deadline);

CREATE INDEX idx_token_tx_wallet_created ON public.token_transactions USING btree (token_wallet_id, created_at);

ALTER TABLE ONLY public.asset_price_history
    ADD CONSTRAINT fk_asset_price_history_asset FOREIGN KEY (asset_id) REFERENCES public.assets(id);

ALTER TABLE ONLY public.asset_quotes
    ADD CONSTRAINT fk_asset_quotes_asset FOREIGN KEY (asset_id) REFERENCES public.assets(id);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.savings_goal_contributions
    ADD CONSTRAINT fk_goal_contributions_goal FOREIGN KEY (savings_goal_id) REFERENCES public.savings_goals(id);

ALTER TABLE ONLY public.incomes
    ADD CONSTRAINT fk_incomes_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.minigame_sessions
    ADD CONSTRAINT fk_minigame_sessions_minigame FOREIGN KEY (minigame_id) REFERENCES public.minigames(id);

ALTER TABLE ONLY public.minigame_sessions
    ADD CONSTRAINT fk_minigame_sessions_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_asset FOREIGN KEY (asset_id) REFERENCES public.assets(id);

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.investment_portfolios
    ADD CONSTRAINT fk_portfolios_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.portfolio_positions
    ADD CONSTRAINT fk_positions_asset FOREIGN KEY (asset_id) REFERENCES public.assets(id);

ALTER TABLE ONLY public.portfolio_positions
    ADD CONSTRAINT fk_positions_portfolio FOREIGN KEY (portfolio_id) REFERENCES public.investment_portfolios(id);

ALTER TABLE ONLY public.projections
    ADD CONSTRAINT fk_projections_goal FOREIGN KEY (savings_goal_id) REFERENCES public.savings_goals(id);

ALTER TABLE ONLY public.projections
    ADD CONSTRAINT fk_projections_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.savings_goals
    ADD CONSTRAINT fk_savings_goals_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.savings
    ADD CONSTRAINT fk_savings_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.token_transactions
    ADD CONSTRAINT fk_token_tx_wallet FOREIGN KEY (token_wallet_id) REFERENCES public.token_wallets(id);

ALTER TABLE ONLY public.token_wallets
    ADD CONSTRAINT fk_token_wallets_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES public.users(id);


